[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies", "../../node_modules"]
solc_version = "0.8.30"

[[profile.default.fs_permissions]]
access = "read"
path = "./testdata"
fs_permissions = [{ access = "read", path = "./testdata"}]

[dependencies]
"@openzeppelin-contracts" = "5.0.1"
forge-std = "1.9.4"

[soldeer]
# whether soldeer manages remappings
remappings_generate = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false

